### PR TITLE
oneliner support

### PR DESCRIPTION
**Pull request by maboiteaspam**
Hi,

Wish you will merge that so i can write

```js
var conf  = require('configstore')(pkg.name, {save: [], savedev:[]});
```

### CODE REVIEW

**Comment by maboiteaspam** [comment]
oops. Lint issues, let s see.

**Comment by maboiteaspam** [comment]
Hi,

Can one maintainer let me know if that __may__ be merged ?

If so I ll be happy to fix my linting issues.

**Comment by sindresorhus** [comment]
Yes, if you fix the lint issues and remove the `var self = this` line.

**Comment by maboiteaspam** [comment]
Lint is fixed now. Also updated the README example. But not the API documentation. Because i feel it s clearer with a real constructor api definition, as it is now. Also because i don t see much how to document that one line capability properly.

**Comment by sindresorhus** [comment]
Actually, I don't think this is a good idea. Sorry. This won't work with ES2015 classes, which we'll eventually switch to.

Just do:

```js
var conf  = (new require('configstore'))(pkg.name, {save: [], savedev:[]});
```

**Pull request closed without merging**
