### PR TITLE
Add `configPath` option

### PR DESCRIPTION
**Pull request by twodayslate**
Added option to change the config.json name

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why?

**Comment by twodayslate** [comment]
Use case would be to change configuration of your application yet remain in the package-name configuration directory. Currently, the only way to change a configuration is to change the package-name.

**Comment by sindresorhus** [comment]
This is a slippery slope. I'd rather we just drop the `globalConfigPath` option and introduce an option to set the full path. That way you have full customizability if you really need it.

**Comment by twodayslate** [comment]
I agree that should be an option as well. I can commit that as well if you would like. Please advise. 

   if(opts.configPath && fs.accessSync(path, fs.F_OK)) {
       this.path = path.join(opts.configPath, pathPrefix);
   } else {
       this.path = path.join(configDi, pathPrefix);
   }

**Comment by sindresorhus** [comment]
```js
this.path = opts.configPath || path.join(configDir, pathPrefix);
```

**Comment by twodayslate** [comment]
I have committed the changes. I still think the pathPrefix option is nice to have.

**Comment by SBoudrias** [comment]
@twodayslate can you drop `pathPrefix`? That's a lot of complexity for what seems to be a non useful feature.

Let's keep the API surface small and only add `configPath` as an option.

**Comment by twodayslate** [comment]
@SBoudrias should be good to go. Let me know if I missed anything (had to switch computers).

**Comment by sindresorhus** [comment]
Look at the diff. It's not correct.

**Comment by twodayslate** [comment]
I see only [one line changed](https://github.com/yeoman/configstore/pull/37#issuecomment-213051694) in index.js. What am I missing @sindresorhus?

**Comment by sindresorhus** [comment]
Pretty clear when you go to the diff view: https://github.com/yeoman/configstore/pull/37/files

**Comment by twodayslate** [comment]
I apologize - I'm not following. Feel free to close this PR if there is no need for this feature.

**Comment by SBoudrias** [comment]
@twodayslate the issue is all the changes in the readme. Can we keep the changes small and focused? If you feel the readme needs improvements, then please open another PR.

I'd really like to get this feature merged asap. Any chance you can update it to make the minimal changes required to make this modification?

**Comment by twodayslate** [comment]
@SBoudrias I have made the readme match the one currently in master

**Comment by SBoudrias** [comment]
@twodayslate If you look here: https://github.com/yeoman/configstore/pull/37/files you'll see that you included a lot of changes to the readme. This is most probably due to a bad rebase/merge on your branch.

**Comment by twodayslate** [comment]
@SBoudrias I reset my repository to upstream and committed the changes. The git history is now cleaner with only one commit.

**Comment by sindresorhus** [comment]
Needs to be documented in the readme and needs a test.

**Comment by SBoudrias** [comment]
Any chance we can get this out soon?

**Comment by addyosmani** [comment]
I think we should land this soon but agree with @sindresorhus on docs updates to the readme and ideally tests. @twodayslate would you be able to help with that?

**Comment by twodayslate** [comment]
Sorry, I haven't touched this in a while and probably won't get a chance to
touch it this week. Feel free to close this as it's only a one-liner.

**Pull request closed without merging**
